// Centralized lucide-react icon exports
export { default as Download } from 'lucide-react/dist/esm/icons/download'
export { default as Mail } from 'lucide-react/dist/esm/icons/mail'
export { default as ExternalLink } from 'lucide-react/dist/esm/icons/external-link'
export { default as Github } from 'lucide-react/dist/esm/icons/github'
export { default as Linkedin } from 'lucide-react/dist/esm/icons/linkedin'
export { default as Code2 } from 'lucide-react/dist/esm/icons/code-2'
export { default as ArrowLeft } from 'lucide-react/dist/esm/icons/arrow-left'
export { default as ChevronRight } from 'lucide-react/dist/esm/icons/chevron-right'
export { default as Filter } from 'lucide-react/dist/esm/icons/filter'
export { default as Gem } from 'lucide-react/dist/esm/icons/gem'
export { default as Shield } from 'lucide-react/dist/esm/icons/shield'
export { default as Smartphone } from 'lucide-react/dist/esm/icons/smartphone'
export { default as Globe } from 'lucide-react/dist/esm/icons/globe'
export { default as Terminal } from 'lucide-react/dist/esm/icons/terminal'
export { default as FileText } from 'lucide-react/dist/esm/icons/file-text'
export { default as Mic } from 'lucide-react/dist/esm/icons/mic'
export { default as ClipboardList } from 'lucide-react/dist/esm/icons/clipboard-list'
export { default as Brain } from 'lucide-react/dist/esm/icons/brain'
export { default as Newspaper } from 'lucide-react/dist/esm/icons/newspaper'
export { default as Users } from 'lucide-react/dist/esm/icons/users'
export { default as Star } from 'lucide-react/dist/esm/icons/star'
export { default as Heart } from 'lucide-react/dist/esm/icons/heart'
export { default as Rocket } from 'lucide-react/dist/esm/icons/rocket'

// Add more exports here as icons are added across the codebase